// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    console.log('[env] all SUPABASE vars:', Object.keys(process.env).filter(k => k.includes('SUPABASE')));
    console.log('[env] SUPABASE_URL:', process.env.SUPABASE_URL);
    console.log('[env] SUPABASE_PUBLISHABLE_KEYS:', process.env.SUPABASE_PUBLISHABLE_KEYS);
    console.log('[env] SUPABASE_PUBLISHABLE_KEY:', process.env.SUPABASE_PUBLISHABLE_KEY);
    throw new Error('ENV DEBUG — check server logs');
    return next();
  },
);
